### Install the VSCode extension "REST Client"
### (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

### GET /
GET http://localhost:4000


### GET /users
GET http://localhost:4000/users
