### Install the VSCode extension "REST Client"
### (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

@baseUrl = http://localhost:4000

### GET all cards
GET {{baseUrl}}/api/cards

### GET a single card
GET {{baseUrl}}/api/cards/1

### GET a not existing card (404)
GET {{baseUrl}}/api/cards/2000

### POST a new card
POST http://localhost:4000/api/cards
Content-Type: application/json

{
  "text": "What is mongoose",
  "votes": 0,
  "author": "Jerry"
}

### PATCH a single card
PATCH {{baseUrl}}/api/cards/1
Content-Type: application/json

{
  "text": "Where does the name Mongo come from?"
}

### DELETE a single card
DELETE {{baseUrl}}/api/cards/1
